[workspace]
members = [
    "core",
    "stager",
    "modules/shell",
    "modules/bof",
    "modules/dotnet",
    "modules/inject",
    "modules/desktop",
    "iso_host",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.release.build-override]
opt-level = "z"
