package utils

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// Golden vector for DeriveKeyAgent — must stay aligned with
// Client/core/src/crypto.rs derive_key (SHA256 × 100_000).
// Regenerated by a one-shot Rust unit if the algorithm changes.
func TestDeriveKeyAgentStable(t *testing.T) {
	base := []byte("SYSTEM_CONFIG_DATA_ENCRYPT_BLOB_") // 32 bytes
	salt := make([]byte, 32)
	copy(salt, []byte("test-salt-value"))

	a := DeriveKeyAgent(base, salt)
	b := DeriveKeyAgent(base, salt)
	if len(a) != 32 {
		t.Fatalf("len %d", len(a))
	}
	if !bytes.Equal(a, b) {
		t.Fatal("not deterministic")
	}

	// Empty salt ≡ 32 zero salt
	z1 := DeriveKeyAgent(base, nil)
	z2 := DeriveKeyAgent(base, make([]byte, 32))
	if !bytes.Equal(z1, z2) {
		t.Fatal("empty salt should match zero salt")
	}
	if bytes.Equal(a, z1) {
		t.Fatal("salted and zero-salt keys must differ")
	}

	// Argon2 path must NOT equal agent path (documents the historical bug)
	argon := DeriveKey(base, salt)
	if bytes.Equal(a, argon) {
		t.Fatal("Argon2 and agent KDF unexpectedly equal")
	}

	t.Logf("agent-kdf=%s argon=%s", hex.EncodeToString(a[:8]), hex.EncodeToString(argon[:8]))
}

func TestDeriveKeyAgentDiffersByBase(t *testing.T) {
	salt := make([]byte, 32)
	copy(salt, "salt")
	a := DeriveKeyAgent([]byte("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), salt)
	b := DeriveKeyAgent([]byte("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"), salt)
	if bytes.Equal(a, b) {
		t.Fatal("different base must produce different key")
	}
}
